### PR TITLE
add linux/stddef.h for musl compatibility

### PR DESCRIPTION
**Pull request by qaqland**
The __always_inline macro is defined in <linux/stddef.h>. While glibc includes this by default, musl does not. This commit explicitly includes <linux/stddef.h> to ensure compatibility with musl libc platforms.

```
In file included from ../tinywl/tinywl.c:8:
../include/scenefx/types/fx/clipped_region.h:18:8: error: unknown type name '__always_inline'
   18 | static __always_inline uint16_t corner_radius_clamp(int radius) {
      |        ^~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by ErikReider** [comment]
Testing in an alpine:edge docker container, I'm also getting `use of undeclared identifier 'unreachable'`. Are you also experiencing this?

**Comment by denyallow24** [comment]
I mentioned a similar thing in #195 and wrote a patch that defines the macro separately, but I find it more sensible to include a dedicated header. Waiting for any changes.

**Comment by qaqland** [comment]
> Testing in an alpine:edge docker container, I'm also getting `use of undeclared identifier 'unreachable'`. Are you also experiencing this?

Since `unreachable()` was introduced in https://github.com/wlrfx/scenefx/commit/b8a41b6 and later removed in https://github.com/wlrfx/scenefx/commit/235ea6d, this PR should now work correctly.

**Comment by YsfOuz** [comment]
@ErikReider

**Review by WillPower3309 — APPROVED** [review]

**Comment by WillPower3309** [comment]
Thanks
